# -*- coding: utf-8 -*-
"""Matplotlib_Assignment_SaiAkhil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpIbNuy8J_VDzp6G6uXcSRmuuERedNi4

Task 1: Line Plot and Scatter Plot
Requirements:

Plot study_hours on X-axis and marks_obtained on Y-axis
Add appropriate labels: "Study Hours" for X-axis, "Marks Obtained" for Y-axis
Add title: "Student Performance Analysis"
Use a blue solid line with circle markers
Display the plot
"""

import matplotlib.pyplot as plt #importing modules
study_hours = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
marks_obtained = [45, 50, 55, 60, 68, 75, 82, 88, 92, 95]
plt.plot(study_hours,marks_obtained,color='blue',marker='o',linestyle='-')#plotting
plt.xlabel('Study Hours') #labeling
plt.ylabel('Marks Obtained')
plt.title('Student Performance Analysis')#displaying
plt.show()

"""Part B: Scatter Plot Create a scatter plot using the same data to show individual data points.

Requirements:

Use study_hours on X-axis and marks_obtained on Y-axis
Use red color for the markers
Add labels and title as in Part A
Display the plot
"""

study_hours = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
marks_obtained = [45, 50, 55, 60, 68, 75, 82, 88, 92, 95]
plt.scatter(study_hours,marks_obtained,color='red')
plt.xlabel('study_hours')
plt.ylabel('marks_obtained')
plt.title('Part A')
plt.show()

"""**Explain the difference between line plot and scatter plot**


---


line plot connect Data points using straight lines, and it shows a variable change over time. For example, I can say stock market price or monthly revenue.

When coming to a scatterplot, it shows individual data points only, without connecting to the straight line, so it shows a relationship between the two variables. They are used to find the patterns. For example, I can say machine learning algorithms came in for large data sets.

**When would you prefer a scatter plot over a line plot?**


---


I choose Scatter plot over a line plot, when  if I want to study the relationship between the two variables, the data points do not fall in natural order. Apart from that, if I want to detect the correlation or, the observations are independent measurements. For a good example, I can say it is like salary vs year of experience and house price vs square foot, etc. A line plot would be misleading in these cases, because it suggests a continuous trend between the points, which is not suitable for these specifications.

**Explain the purpose of adding labels and titles to plots**


---


Adding labels and titles is like describing the overall meaning of the graph. It helps to immediately understand what the plot represents. Apart from that, it explains which axis represents what and identifies the multiple lines of the database in a graph.

**Task 2: Bar Chart Comparison
Create a grouped bar chart to compare Math and Science scores of students.**

Requirements:

Display student names on X-axis
Display scores on Y-axis
Show Math scores in blue color and Science scores in orange color
Add a legend to distinguish between Math and Science
Add title: "Student Performance: Math vs Science"
Add appropriate axis labels
Display the plot
"""

import numpy as np
students = ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
math_scores = [85, 78, 92, 88, 76]
science_scores = [78, 85, 88, 82, 90]
x=np.arange(len(students))#position of students
width=0.35#width of each bar
plt.bar(x-width/2,math_scores,width,color='blue',label='mathsscore')
plt.bar(x+width/2,science_scores,width,color='orange',label='sciencescore')
plt.xlabel('students')
plt.ylabel('scores')
plt.title('Student Performance: Math vs Science')
plt.xticks(x,students)#here x will represent the each student name instead of 0,1,2
plt.legend()
plt.show()

"""Explain why bar charts are useful for comparing categories

*   These are useful because they show value for different groups or categories. Each category has a bar, and the height of the bar shows the value. This makes it very easy to compare which category has higher value or lower value.



---


Explain how to create grouped bars (bars side-by-side) in Matplotlib


* Courses are useful when you want to compare multiple values with the same category. These are the following steps:
1. Create positions for the category using X.
2. Define a bar width.
3. Draw one set of bars slightly left.
4. Draw the other set of bars slightly right, as shown in above code.



---


What does the legend help achieve in this visualization?


*   Visualization legends explain what each color or bar represents. In the above example, the blue bar represents the Max code, and the orange bar represents the Science code. By this, it will be helpful for the viewers who understand the chart easily when multiple data sets are shown.

Task 3: Histogram and Pie Chart
Part A: Histogram Create a histogram to show the distribution of marks across all 50 students.

Requirements:

Use the marks_distribution data
Set number of bins to 10
Use green color for the bars
Add title: "Distribution of Student Marks"
Add X-axis label: "Marks Range"
Add Y-axis label: "Number of Students"
Display the plot
"""

marks_distribution = [45, 52, 58, 63, 67, 71, 55, 60, 65, 70,
                      75, 80, 85, 90, 48, 54, 59, 64, 69, 74,
                      79, 84, 89, 50, 56, 62, 68, 72, 78, 83,
                      88, 46, 53, 61, 66, 73, 77, 82, 87, 92,
                      49, 57, 64, 70, 76, 81, 86, 91, 95, 51]
plt.hist(marks_distribution,bins=10,color='green',edgecolor='black')
##bins are value ranges used to group data like 50-60 ia abin 60-70 is a bin all values in this rage comes into this bin
plt.title('Distribution of Student Marks')
plt.xlabel('Marks Range')
plt.ylabel('Number of Students')
plt.show()

"""Part B: Pie Chart Create a pie chart to show the distribution of students across different activities.

Requirements:

Use activities for labels and student_count for values



Display percentage values on the slices
Use the explode feature to highlight the "Sports" category (explode value: 0.1)
Add title: "Student Activity Distribution"
Display the plot
"""

activities = ['Sports', 'Music', 'Arts', 'Drama', 'Debate']
student_count = [45, 30, 25, 15, 35]
explode=[0.1,0,0,0,0]
plt.pie(student_count,labels=activities,autopct='%1.1f%%',explode=explode)
## autopct is used to display percentage values n explode is used to pull one slice outside slightly in above case it is sports n represented as 0.1
plt.title('Student Activity Distribution')
plt.show()

"""Explain what histograms tell us about data that tables cannot


1.   A table shows numbers one by one, but a histogram shows the overall pattern of the data. With a histogram, we can quickly see most of the values, whether the values are spread out or closer together, whether they are high or very low values, and the shape of the data. A table gives the detail, but a histogram gives a very big picture.

Explain what "bins" mean in a histogram and why choosing the right number matters

*  Bins are value ranges that are used to group the data. For example, in the above marks, the values are from 40 to 100 bins. Many group them, like 40 to 50, 50 to 60, 60 to 70, based upon the number of bins. Each bar shows how many values fall in that range.
It's like step one:
- Too few bins: the chart becomes too simple and important details are hidden.
- Too many bins: the chart becomes too crowded and hard to read.
The right number of bins helps to read the data clearly.



Explain when pie charts are appropriate and when they should be avoided


*   Use pie charts when you want to show parts of one whole category.
1. The number of categories is small.
2. You want to show the percentages.
For example, how many students are divided among sports, music, and art? This is a good example.

* When to avoid a pie chart means there are too many categories, values are very close to each other, and you want an accurate comparison between those categories. In those cases, I avoid using pie charts.


"""